import React,{useEffect,useState}from"react";
import{ActivityIndicator,Alert,Image,Pressable,ScrollView,StyleSheet,Text,View}from"react-native";
import NetInfo from"@react-native-community/netinfo";
import{inspectImage,recognizeText}from"./ocr";
import{getVisionConfig,OpenAICompatibleFoodVisionProvider,StructuredResult}from"./vision";
import{loadScannerPreferences,saveScannerPreferences}from"./preferences";
import{ProductCandidate,ProductSearchInput,searchProducts}from"./productSearch";
import{countScanMetric,logScanEvent,saveScanDebug}from"./scanMetrics";

type Props={photo:string;barcode?:string;back:()=>void;onCandidate:(candidate:ProductCandidate)=>void;onContinue:(mode:"nutrition"|"ingredients")=>void;onManual:(draft:Record<string,string>)=>void};
type Clues={brand:string;productName:string;variant:string;quantity:string;category:string;keywords:string[];barcode:string};
const teal="#168F86",deep="#163F3C",muted="#66817F";
function localClues(text:string,barcode?:string):Clues{const lines=text.split(/\n+/).map(x=>x.trim()).filter(x=>x.length>=2&&!/^(净含量|配料|营养成分|生产日期|保质期)/.test(x)),quantity=text.match(/\b\d+(?:\.\d+)?\s*(?:mL|ml|L|克|kg|g)\b/i)?.[0]||"",visible=lines.filter(x=>!/^\d+$/.test(x)).slice(0,8),foundBarcode=text.match(/\b\d{8,14}\b/)?.[0]||barcode||"";return{brand:visible[0]||"",productName:visible[1]||visible[0]||"",variant:visible[2]||"",quantity,category:"",keywords:visible,barcode:foundBarcode}}
function mergeClues(local:Clues,vision?:StructuredResult):Clues{return{brand:vision?.brand||local.brand,productName:vision?.product_name||local.productName,variant:vision?.variant||local.variant,quantity:vision?.quantity||local.quantity,category:vision?.category||local.category,keywords:[...(vision?.visible_text??[]),...local.keywords].filter((x,i,a)=>x&&a.indexOf(x)===i).slice(0,10),barcode:vision?.barcode||local.barcode}}
async function consent(){const p=await loadScannerPreferences();if(p.onlineConsentAsked)return p.onlineEnhancement;return new Promise<boolean>(resolve=>Alert.alert("联网识别商品","为了识别商品包装，护康可以将当前食品照片发送到联网识别服务进行分析。",[{text:"暂不开启",style:"cancel",onPress:async()=>{await saveScannerPreferences({...p,onlineConsentAsked:true,onlineEnhancement:false});resolve(false)}},{text:"允许",onPress:async()=>{await saveScannerPreferences({...p,onlineConsentAsked:true,onlineEnhancement:true});resolve(true)}}],{cancelable:false}))}
export default function ProductRecognitionScreen({photo,barcode,back,onCandidate,onContinue,onManual}:Props){const[status,setStatus]=useState("正在检查照片…"),[failure,setFailure]=useState(""),[clues,setClues]=useState<Clues>({brand:"",productName:"",variant:"",quantity:"",category:"",keywords:[],barcode:barcode||""}),[candidates,setCandidates]=useState<ProductCandidate[]>([]),[working,setWorking]=useState(true),[searched,setSearched]=useState(false),[networkFailed,setNetworkFailed]=useState(false);
 useEffect(()=>{let cancelled=false;(async()=>{try{const quality=await inspectImage(photo);await saveScanDebug({quality});if(quality.tooDark)throw new Error("光线有点暗，换个亮一点的位置。");if(quality.tooBright)throw new Error("照片有些过亮，降低光线再拍。");if(quality.hasGlare)throw new Error("包装反光较强，换个角度试试。");if(quality.tooBlurry)throw new Error("照片有点糊，再靠近一点。");if(quality.tooSmall)throw new Error("完整包装太小，请靠近一点再拍。");await countScanMetric("photoValid");setStatus("正在读取包装文字…");let raw="";try{raw=await recognizeText(photo)}catch{}if(raw.trim())await countScanMetric("ocrText");await logScanEvent("PRODUCT_LOCAL_TEXT_RECEIVED",{length:raw.length});let merged=localClues(raw,barcode),visionResult:StructuredResult|undefined;const net=await NetInfo.fetch();if(net.isConnected!==false&&await consent()){const config=await getVisionConfig();if(config.apiKey){setStatus("正在识别商品包装…");try{visionResult=await new OpenAICompatibleFoodVisionProvider(config).analyzeProduct(photo);merged=mergeClues(merged,visionResult);await countScanMetric("visionSuccess")}catch(e){await logScanEvent("VISION_REQUEST_FAILED",{error:String(e)})}}}if(cancelled)return;setClues(merged);await saveScanDebug({rawText:raw,detectedType:"product_packaging",parse:merged,provider:visionResult?"online+local":"local"});if(!merged.productName&&!merged.brand&&!merged.keywords.length){setFailure("没有看清完整商品包装，再拍一张试试。");return}setStatus("正在查找可能的商品…");const input:ProductSearchInput={barcode:merged.barcode,brand:merged.brand,productName:merged.productName,variant:merged.variant,quantity:merged.quantity,keywords:merged.keywords},result=await searchProducts(input);if(cancelled)return;setCandidates(result.candidates);setSearched(true);setNetworkFailed(result.network==="offline"||result.network==="error");await logScanEvent("RESULT_SCREEN",{candidateCount:result.candidates.length,network:result.network})}catch(e){setFailure(e instanceof Error&&/。$/.test(e.message)?e.message:"照片没有准备好，请重新拍摄。");await logScanEvent("PRODUCT_RECOGNITION_STOPPED",{error:String(e)})}finally{if(!cancelled)setWorking(false)}})();return()=>{cancelled=true}},[photo]);
 useEffect(()=>{if(searched)logScanEvent("STATE_UPDATE",{candidateCount:candidates.length}).catch(()=>{})},[searched,candidates.length]);
 const draft={brand:clues.brand,name:clues.productName,variant:clues.variant,category:clues.category,netContent:clues.quantity.match(/[\d.]+/)?.[0]||"",netContentUnit:/ml/i.test(clues.quantity)?"mL":/g|克/i.test(clues.quantity)?"g":"",barcode:clues.barcode,imageUri:photo};
 return <ScrollView contentContainerStyle={p.page}><View style={p.header}><Pressable onPress={back} style={p.back}><Text style={p.backText}>‹</Text></Pressable><Text style={p.headerTitle}>识别商品</Text><View style={{width:40}}/></View><Image source={{uri:photo}} style={p.photo} resizeMode="contain"/><Text style={p.status}>{working?status:"刚才拍到的商品"}</Text>{working&&<ActivityIndicator color={teal}/>} {!!failure&&<View style={p.warning}><Text style={p.warningText}>{failure}</Text><Pressable onPress={back}><Text style={p.action}>重新拍摄</Text></Pressable></View>}{!working&&searched&&candidates.length>0&&<View style={p.block}><Text style={p.title}>{candidates.length===1?"找到了这款商品":"我找到了几个可能的商品"}</Text>{candidates.map(c=><View key={c.key} style={p.candidate}>{!!c.imageUri&&<Image source={{uri:c.imageUri}} style={p.thumb}/>}<View style={{flex:1,gap:3}}><Text style={p.candidateName}>{c.brand} {c.name}</Text><Text style={p.sub}>{[c.variant,c.quantity].filter(Boolean).join(" · ")||"规格未记录"}</Text></View><Pressable style={p.choose} onPress={()=>onCandidate(c)}><Text style={p.chooseText}>就是这个</Text></Pressable></View>)}<Pressable onPress={()=>setCandidates([])}><Text style={p.action}>都不是</Text></Pressable></View>}{!working&&searched&&candidates.length===0&&<View style={p.block}><Text style={p.title}>暂时没有找到完全匹配的商品</Text>{[["品牌",clues.brand],["商品名",clues.productName],["口味 / 款式",clues.variant],["规格",clues.quantity]].map(([a,b])=><View key={a} style={p.info}><Text style={p.sub}>{a}</Text><Text style={p.infoValue}>{b||"未识别"}</Text></View>)}{networkFailed&&<Text style={p.network}>当前网络不可用，稍后可以重新搜索。</Text>}<Pressable style={p.main} onPress={()=>onContinue("nutrition")}><Text style={p.mainText}>继续拍营养成分表</Text></Pressable><Pressable style={p.light} onPress={()=>onContinue("ingredients")}><Text style={p.lightText}>继续拍配料表</Text></Pressable><Pressable onPress={()=>onManual(draft)}><Text style={p.action}>手动创建</Text></Pressable></View>}</ScrollView>}
const p=StyleSheet.create({page:{padding:20,paddingBottom:44,gap:13,backgroundColor:"#F2FAF8",minHeight:"100%"},header:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},back:{width:40,height:40,borderRadius:20,backgroundColor:"white",alignItems:"center",justifyContent:"center"},backText:{fontSize:28,color:deep,marginTop:-3},headerTitle:{fontSize:20,fontWeight:"900",color:deep},photo:{width:"100%",height:250,borderRadius:24,backgroundColor:"#DDEAE7"},status:{fontSize:13,color:muted,textAlign:"center"},warning:{backgroundColor:"#FFF3DF",borderRadius:20,padding:18,gap:10},warningText:{fontSize:15,color:deep,lineHeight:22},block:{backgroundColor:"white",borderRadius:24,padding:18,gap:12},title:{fontSize:20,fontWeight:"900",color:deep},candidate:{flexDirection:"row",alignItems:"center",gap:10,paddingVertical:10,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:"#D8E8E5"},thumb:{width:54,height:54,borderRadius:12,backgroundColor:"#EAF2F0"},candidateName:{fontSize:14,fontWeight:"800",color:deep},sub:{fontSize:12,color:muted},choose:{backgroundColor:"#DFF4F0",borderRadius:13,paddingHorizontal:11,paddingVertical:9},chooseText:{fontSize:12,color:teal,fontWeight:"800"},action:{textAlign:"center",color:teal,fontWeight:"800",padding:7},info:{flexDirection:"row",justifyContent:"space-between",gap:12},infoValue:{fontSize:14,fontWeight:"700",color:deep,flex:1,textAlign:"right"},network:{fontSize:13,color:"#8A5A13",backgroundColor:"#FFF3DA",padding:10,borderRadius:12},main:{minHeight:50,borderRadius:16,backgroundColor:teal,alignItems:"center",justifyContent:"center"},mainText:{color:"white",fontWeight:"900"},light:{minHeight:48,borderRadius:16,backgroundColor:"#DFF4F0",alignItems:"center",justifyContent:"center"},lightText:{color:teal,fontWeight:"800"}});
